import type {SchemaTypeDefinition} from 'sanity'
import {
  article,
  book,
  bookChapter,
  bookPart,
  caseStudy,
  event,
  framework,
  institution,
  leadMagnet,
  mediaItem,
  newsletterIssue,
  person,
  program,
  redirect,
  siteSettings,
} from './documents'
import {assetMetadata, citation, controlledFile, controlledImage, cta, faqItem, linkItem, portableText, seo} from './objects'

export const schemaTypes: SchemaTypeDefinition[] = [
  assetMetadata,
  controlledImage,
  controlledFile,
  portableText,
  linkItem,
  cta,
  citation,
  faqItem,
  seo,
  siteSettings,
  person,
  book,
  bookPart,
  bookChapter,
  framework,
  article,
  leadMagnet,
  program,
  newsletterIssue,
  mediaItem,
  caseStudy,
  institution,
  event,
  redirect,
]
